import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ThemeProvider } from '@/theme-provider';
import { Header } from '@/app/components/header';
import AppBar from '@/app/components/app-bar';
import NavigationPane from '@/app/components/navigation-pane';
import styles from './layout.module.css';
import Footer from '@/app/components/footer';

import './globals.css';
import { Separator } from '@/components/ui/separator';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className={styles.app}>
            <AppBar />
            <Header />
            <Separator orientation="horizontal" />
            <div className={styles.content}>
              <NavigationPane />
              <Separator orientation="vertical" />
              {children}
            </div>
            <Separator orientation="horizontal" />
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
